dist: trusty
language: node_js

node_js:
  - "6"

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

install:
  - npm install

script:
  - alias firefox-bin='firefox'
  - which firefox
  - firefox --version
  - which firefox-bin
  - firefox-bin --version
  - which google-chrome
  - google-chrome --version
  - npm run test

cache:
  directories:
  - node_modules

addons:
  firefox: latest