sudo: required
dist: trusty
language: node_js

node_js:
  - "node"

install:
  - npm install

script:
  - which firefox
  - firefox --version
  - which google-chrome
  - google-chrome --version
  - npm run test

cache:
  directories:
  - node_modules

addons:
  firefox: latest
  chrome: stable

